version: '3.9'
services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: Starterpack_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
